# Generated by Django 6.0.9 on 2026-10-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_officemembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientcompany',
            new_name='organizatio_office__26c3f5_idx',
            old_name='organizations_office__a3572d_idx',
        ),
    ]
